name: Release

on:
  push:
    tags:
      - '*'
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Stuff
        run: |
          echo "Hello World"